INSERT INTO PERSON_TBL (FIRST_NAME, LAST_NAME, USERNAME, DATE_OF_BIRTH, AGE, SSN, GENDER, EMAIL) VALUES ('Erica','Wright','erwright', '02/26/1971', 0, '123-45-6789', 'FEMALE', 'erwright@me.com');
INSERT INTO PERSON_TBL (FIRST_NAME, LAST_NAME, USERNAME, DATE_OF_BIRTH, AGE, SSN, GENDER, EMAIL) VALUES ('Patrick','Baril','pabaril','01/23/1982', 0, '123-45-6780', 'MALE', 'pabaril@gmail.com');
INSERT INTO PERSON_TBL (FIRST_NAME, LAST_NAME, USERNAME, DATE_OF_BIRTH, AGE, SSN, GENDER, EMAIL) VALUES ('Christopher','Martin','chmartin','03/21/1966', 0, '123-45-6781', 'MALE', 'chmartin@yahoo.com');
INSERT INTO PERSON_TBL (FIRST_NAME, LAST_NAME, USERNAME, DATE_OF_BIRTH, AGE, SSN, GENDER, EMAIL) VALUES ('Daniel','Maman','damaman','10/25/1977', 0, '123-45-6782', 'MALE', 'damaman@hotmail.com');
INSERT INTO PERSON_TBL (FIRST_NAME, LAST_NAME, USERNAME, DATE_OF_BIRTH, AGE, SSN, GENDER, EMAIL) VALUES ('Jill','Scott','jiscott','04/04/1972', 0, '123-45-6783', 'FEMALE', 'jiscott@sbcglobal.net');

INSERT INTO ADDRESS_TBL (LINE_ONE, LINE_TWO, CITY, STATE, ZIP) VALUES ('1234 Davis St.', 'Apt. 1', 'Grand Prairie', 'TX', '75052');
INSERT INTO ADDRESS_TBL (LINE_ONE, LINE_TWO, CITY, STATE, ZIP) VALUES ('711 George Dr.', '', 'Paris', 'TX', '75460');
INSERT INTO ADDRESS_TBL (LINE_ONE, LINE_TWO, CITY, STATE, ZIP) VALUES ('826 Summer Ave.', 'No. 4', 'Chicago', 'IL', '60605-1234');

INSERT INTO PHONE_TBL (PHONE_NUMBER, PHONE_TYPE, PERSON_ID) VALUES ('806-413-2785', 'Mobile', 1);
INSERT INTO PHONE_TBL (PHONE_NUMBER, PHONE_TYPE, PERSON_ID) VALUES ('520-893-4205', 'Home', 1);
INSERT INTO PHONE_TBL (PHONE_NUMBER, PHONE_TYPE, PERSON_ID) VALUES ('214-890-2045', 'Business', 1);