INSERT INTO PERSON_TBL (FIRST_NAME, LAST_NAME, USERNAME, DATE_OF_BIRTH, SSN, GENDER, EMAIL) VALUES ('Patrick','Baril','pabaril', PARSEDATETIME('1982-01-23', 'yyyy-MM-dd'), '123-45-6780', 'MALE', 'pabaril@gmail.com');
INSERT INTO PERSON_TBL (FIRST_NAME, LAST_NAME, USERNAME, DATE_OF_BIRTH, SSN, GENDER, EMAIL) VALUES ('Daniel','Maman','damaman', PARSEDATETIME('1977-10-25', 'yyyy-MM-dd'), '123-45-6782', 'MALE', 'damaman@hotmail.com');
INSERT INTO PERSON_TBL (FIRST_NAME, LAST_NAME, USERNAME, DATE_OF_BIRTH, SSN, GENDER, EMAIL) VALUES ('Christopher','Martin','chmartin', PARSEDATETIME('1966-03-21', 'yyyy-MM-dd'), '123-45-6781', 'MALE', 'chmartin@yahoo.com');
INSERT INTO PERSON_TBL (FIRST_NAME, LAST_NAME, USERNAME, DATE_OF_BIRTH, SSN, GENDER, EMAIL) VALUES ('Jill','Scott','jiscott', PARSEDATETIME('1972-04-04', 'yyyy-MM-dd'), '123-45-6783', 'FEMALE', 'jiscott@sbcglobal.net');
INSERT INTO PERSON_TBL (FIRST_NAME, LAST_NAME, USERNAME, DATE_OF_BIRTH, SSN, GENDER, EMAIL) VALUES ('Erica','Wright','erwright', PARSEDATETIME('1971-02-26', 'yyyy-MM-dd'), '123-45-6789', 'FEMALE', 'erwright@me.com');

UPDATE PERSON_TBL SET AGE = DATEDIFF(YEAR, DATE_OF_BIRTH, CURRENT_DATE);

INSERT INTO ADDRESS_TBL (LINE_ONE, LINE_TWO, CITY, STATE, ZIP) VALUES ('1234 Davis St.', 'Apt. 1', 'Grand Prairie', 'TX', '75052');
INSERT INTO ADDRESS_TBL (LINE_ONE, LINE_TWO, CITY, STATE, ZIP) VALUES ('711 George Dr.', '', 'Paris', 'TX', '75460');
INSERT INTO ADDRESS_TBL (LINE_ONE, LINE_TWO, CITY, STATE, ZIP) VALUES ('826 Summer Ave.', 'No. 4', 'Chicago', 'IL', '60605-1234');

INSERT INTO PHONE_TBL (PHONE_NUMBER, PHONE_TYPE, PERSON_ID) VALUES ('806-413-2785', 'MOBILE', 2);
INSERT INTO PHONE_TBL (PHONE_NUMBER, PHONE_TYPE, PERSON_ID) VALUES ('520-893-4205', 'HOME', 1);
INSERT INTO PHONE_TBL (PHONE_NUMBER, PHONE_TYPE, PERSON_ID) VALUES ('214-890-2045', 'BUSINESS', 1);