INSERT INTO PERSON_TBL (FIRST_NAME, LAST_NAME, USERNAME, DATE_OF_BIRTH, SSN, GENDER, EMAIL) VALUES ('Erica','Wright','erwright','02/26/1971', '123-45-6789', 'female', 'erwright@me.com');
INSERT INTO PERSON_TBL (FIRST_NAME, LAST_NAME, USERNAME, DATE_OF_BIRTH, SSN, GENDER, EMAIL) VALUES ('Patrick','Baril','pabaril','01/23/1982', '123-45-6780', 'male', 'pabaril@gmail.com');
INSERT INTO PERSON_TBL (FIRST_NAME, LAST_NAME, USERNAME, DATE_OF_BIRTH, SSN, GENDER, EMAIL) VALUES ('Christopher','Martin','chmartin','03/21/1966', '123-45-6781', 'male', 'chmartin@yahoo.com');
INSERT INTO PERSON_TBL (FIRST_NAME, LAST_NAME, USERNAME, DATE_OF_BIRTH, SSN, GENDER, EMAIL) VALUES ('Daniel','Maman','damaman','10/25/1977', '123-45-6782', 'male', 'damaman@hotmail.com');
INSERT INTO PERSON_TBL (FIRST_NAME, LAST_NAME, USERNAME, DATE_OF_BIRTH, SSN, GENDER, EMAIL) VALUES ('Jill','Scott','jiscott','04/04/1972', '123-45-6783', 'female', 'jiscott@sbcglobal.net');

INSERT INTO ADDRESS_TBL (LINE_ONE, LINE_TWO, CITY, STATE, ZIP) VALUES ('1234 Davis St.', 'Apt. 1', 'Grand Prairie', 'TX', '75052');
INSERT INTO ADDRESS_TBL (LINE_ONE, LINE_TWO, CITY, STATE, ZIP) VALUES ('711 George Dr.', '', 'Paris', 'TX', '75460');
INSERT INTO ADDRESS_TBL (LINE_ONE, LINE_TWO, CITY, STATE, ZIP) VALUES ('826 Summer Ave.', 'No. 4', 'Chicago', 'IL', '60605');

INSERT INTO PHONE_TBL (PHONE_NUMBER, PHONE_TYPE) VALUES ('8064132785', 'Mobile');
INSERT INTO PHONE_TBL (PHONE_NUMBER, PHONE_TYPE) VALUES ('5208934205', 'Home');
INSERT INTO PHONE_TBL (PHONE_NUMBER, PHONE_TYPE) VALUES ('2147132785', 'Business');